name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.1
      with:
        cli: 1.10.1.693

    - name: Install dependencies
      run: clojure -e "(println \"Fetched deps\")"

    - name: Run tests and generate code coverage
      run: clojure -M:coverage

    - name: Send coverage results to codecov
      run: CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} bash <(curl -s https://codecov.io/bash)
